elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
  volumes:
    - "/usr/share/elasticsearch/data:/usr/share/elasticsearch/data"

kibana:
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
