redis-master:
  image: saidie/redis:unstable
  ports:
    - "6379:6379"
  volumes:
     - ./redis/data/master:/data
  command: [/data/redis.conf]

redis-slave:
  image: saidie/redis:unstable
  ports:
    - "6380:6379"
  volumes:
     - ./redis/data/slave:/data
  links:
    - redis-master
  command: [/data/redis.conf]
